MANIFEST_DIR = 'manifests'
PROGRESS_DIR = 'in_progress'
METADATA_FORMAT = 'DDD:ddd:{}:mpeg21.didl.xml.gz'
NEWSPAPER_FORMAT = 'DDD_{}'
TARBALL_FORMAT = NEWSPAPER_FORMAT + '.tgz'
ARTICLE_FORMAT = NEWSPAPER_FORMAT + '_{}_articletext.xml'
